{{- if not .Values.global.omitSidecarInjectorConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: sidecar-injector
    istio: sidecar-injector
data:
  values: |-
    {{ .Values | toJson }}

  config: |-
    policy: {{ .Values.global.proxy.autoInject }}
{{ .Files.Get "files/injection-template.yaml" | indent 4 }}
{{- end }}
