{{- if .Values.kiali.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali-operator
subjects:
  - kind: ServiceAccount
    name: kiali-operator-service-account
    namespace: {{ .Values.kiali.operator.namespace }}
{{- end }}
