{{- if .Values.kiali.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-operator
  namespace: {{ .Values.kiali.operator.namespace }}
  labels:
    app: kiali-operator
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.kiali.operator.replicaCount }}
  selector:
    matchLabels:
      app: kiali-operator
  template:
    metadata:
      name: kiali-operator
      labels:
        app: kiali-operator
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
        {{- if .Values.kiali.operator.podAnnotations }}
{{ toYaml .Values.kiali.operator.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: kiali-operator-service-account
{{- if .Values.global.priorityClassName }}
      priorityClassName: "{{ .Values.global.priorityClassName }}"
{{- end }}
      containers:
      - name: ansible
        command:
        - /usr/local/bin/ao-logs
        - /tmp/ansible-operator/runner
        - stdout
        image: "{{ .Values.kiali.operator.hub }}/{{ .Values.kiali.operator.image }}:{{ .Values.kiali.operator.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
          readOnly: true
      - name: operator
        image: "{{ .Values.kiali.operator.hub }}/{{ .Values.kiali.operator.image }}:{{ .Values.kiali.operator.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "kiali-operator"
        resources:
{{- if .Values.kiali.operator.resources }}
{{ toYaml .Values.kiali.operator.resources | indent 10 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 10 }}
{{- end }}
      volumes:
      - name: runner
        emptyDir: {}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
{{- end }}
