apiVersion: v1
kind: Service
metadata:
  name: istio-galley
  namespace: {{ .Release.Namespace }}
  labels:
    app: galley
    istio: galley
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 443
    name: https-validation
  - port:  {{ .Values.global.monitoringPort }}
    name: http-monitoring
  - port: 9901
    name: grpc-mcp
  - port: 15019
    name: grpc-tls-mcp
  selector:
    istio: galley
