{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
{{- if $gateway.autoscaleMin }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: egressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: egressgateway
    chart: egressgateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  maxReplicas: {{ $gateway.autoscaleMax }}
  minReplicas: {{ $gateway.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: egressgateway
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $gateway.cpu.targetAverageUtilization }}
---
{{- end }}
