{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: egressgateway
    chart: egressgateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: {{ .Release.Namespace }}
spec:
  replicas: {{ $gateway.replicaCount }}
  template:
    metadata:
      labels:
        chart: egressgateway
        heritage: {{ $.Release.Service }}
        release: {{ $.Release.Name }}
        version: {{ $.Chart.Version }}
        app: egressgateway
        istio: {{ .Release.Namespace }}
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
{{- if $gateway.podAnnotations }}
{{ toYaml $gateway.podAnnotations | indent 8 }}
{{ end }}
    spec:
{{- if .Values.global.priorityClassName }}
      priorityClassName: "{{ .Values.global.priorityClassName }}"
{{- end }}
{{- if .Values.global.proxy.enableCoreDump }}
      initContainers:
        - name: enable-core-dump
{{- if contains "/" .Values.global.proxy_init.image }}
          image: "{{ .Values.global.proxy_init.image }}"
{{- else }}
          image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image | default "proxy_init" }}:{{ .Values.global.tag }}"
{{- end }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:
            - -c
            - sysctl -w kernel.core_pattern=/var/lib/istio/core.proxy && ulimit -c unlimited
          securityContext:
            privileged: true
{{- end }}
      containers:
        - name: istio-proxy
{{- if contains "/" .Values.global.proxy.image }}
          image: "{{ .Values.global.proxy.image }}"
{{- else }}
          image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
          ports:
            {{- range $key, $val := $gateway.ports }}
            - containerPort: {{ $val.port }}
            {{- end }}
            {{- range $key, $val := $gateway.meshExpansionPorts }}
            - containerPort: {{ $val.port }}
            {{- end }}
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
          args:
          - proxy
          - router
{{- if .Values.global.proxy.proxyDomain }}
          - --domain
          - {{ .Values.global.proxy.proxyDomain }}
{{- end }}
          - --log_output_level
          - '{{ $gateway.debug | default "info" }}'
          - --proxyLogLevel
          - '{{ $gateway.debug | default "info" }}'
          - --drainDuration
          - '{{ $gateway.drainDuration }}' #drainDuration
          - --parentShutdownDuration
          - '1m0s' #parentShutdownDuration
          - --connectTimeout
          - '{{ $gateway.connectTimeout }}' #connectTimeout
          - --serviceCluster
          - egressgateway{{ $gateway.suffix | default "" }}
          - --zipkinAddress
        {{- if .Values.global.tracer.zipkin.address }}
          - {{ .Values.global.tracer.zipkin.address }}
        {{- else if .Values.global.telemetryNamespace }}
          - zipkin.{{ .Values.global.telemetryNamespace }}:9411
        {{- else }}
          - zipkin:9411
        {{- end }}
          - --proxyAdminPort
          - "15000"
        {{- if .Values.global.controlPlaneSecurityEnabled }}
          - --controlPlaneAuthPolicy
          - MUTUAL_TLS
          - --discoveryAddress
          {{- if .Values.global.istioNamespace }}
          - istio-pilot.{{ .Values.global.istioNamespace }}:15011
          {{- else }}
          - istio-pilot:15011
          {{- end }}
        {{- else }}
          - --controlPlaneAuthPolicy
          - NONE
          - --discoveryAddress
          {{- if .Values.global.istioNamespace }}
          - istio-pilot.{{ .Values.global.istioNamespace }}:15010
          {{- else }}
          - istio-pilot:15010
          {{- end }}
        {{- end }}
          resources:
{{- if $gateway.resources }}
{{ toYaml $gateway.resources | indent 12 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 12 }}
{{- end }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name             
          {{- if $gateway.env }}
          {{- range $key, $val := $gateway.env }}
          - name: {{ $key }}
            value: {{ $val }}
          {{- end }}
          {{ end }}
          volumeMounts:
          {{ if .Values.global.sds.enabled }}
          - name: sdsudspath
            mountPath: /var/run/sds
          {{- end }}
          - name: istio-certs
            mountPath: /etc/certs
            readOnly: true
          {{- range $gateway.secretVolumes }}
          - name: {{ .name }}
            mountPath: {{ .mountPath | quote }}
            readOnly: true
          {{- end }}
{{- if $gateway.additionalContainers }}
{{ toYaml $gateway.additionalContainers | indent 8 }}
{{- end }}
      volumes:
      {{ if .Values.global.sds.enabled }}
      - name: sdsudspath
        hostPath:
          path: /var/run/sds
      {{- end }}
      - name: istio-certs
        secret:
          secretName: istio.default
          optional: true
      {{- range $gateway.secretVolumes }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName | quote }}
          optional: true
      {{- end }}
      {{- range $gateway.configVolumes }}
      - name: {{ .name }}
        configMap:
          name: {{ .configMapName | quote }}
          optional: true
      {{- end }}
{{- if .Values.global.arch }}
      affinity:
      {{- include "nodeaffinity" $ | indent 6 }}
{{- end }}
---
