{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: egressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: egressgateway
    release: {{ .Release.Name }}
    istio: egressgateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: egressgateway
      release: {{ .Release.Name }}
      istio: egressgateway
{{- end }}
