# helm template istio-1.2.2/install/kubernetes/helm/istio --name istio --namespace istio-system > istio.yaml
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gen-istio.yaml


