---

# s3, git, time, github-release, registry-image,
# pool - serialize access to external systems
# git - can also push
resources:
  - name: 24h
    type: time
    source: {interval: 24h}

  - name: istio-installer #DO NOT SET TO FORK - for testing use another pipeline and pause this one
    type: git
    source:
      uri: "https://github.com/istio/istio-installer"
  - name: istio-master
    type: git
    source:
      uri: "https://github.com/istio/istio"
      branch: master
      
jobs:
  - name: install
    serial_groups: [ cluster ]
    plan:
    - get: 24h
      trigger: true
    - get: istio-installer
      trigger: true
  
    - task: log-used-repo
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ecx
          - |
            cd istio-installer
            git remote -v
            git branch

    - task: install-master-daily
      params: &params-master-daily
        TAG: master-latest-daily
        HUB: gcr.io/istio-release
        KUBECONFIG: ((KUBECONFIG))
        # Remove overly generous resource request to avoid unnecessarily scaling up k8s nodes
        RESOURCES_FLAGS: "--set global.resources.requests.cpu=0m --set resources.requests.cpu=0 --set resources.requests.memory=0 --set global.proxy.resources.requests.cpu=0 --set global.proxy.resources.requests.memory=0"
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            istio-installer/bin/cleanup.sh
            istio-installer/bin/install.sh
    
  - name: test-after-install
    serial_groups: [ cluster ]
    plan:
    - get: istio-installer
      passed: [ install ]
      trigger: true
    - get: istio-master
      trigger: false
    - get: 24h
      trigger: true
      passed: [install]
    - task: install-bookinfo
      params:
        KUBECONFIG: ((KUBECONFIG))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-master
            path: src/github.com/istio/istio
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            istio-installer/bin/test.sh --skip-cleanup src/github.com/istio/istio/

  - name: install-old-master # we probably want 1.1 here, but we would need an old installer
    serial_groups: [ cluster ]
    plan:
    - get: 24h
      trigger: true
      passed: [ test-after-install ]
    - get: istio-installer
      trigger: true
      passed: [ test-after-install ]

    - task: install-old-master
      params: &params-master-old
        TAG: master-20190506-09-16
        HUB: gcr.io/istio-release
        RESOURCES_FLAGS: "--set global.resources.requests.cpu=0m --set resources.requests.cpu=0 --set resources.requests.memory=0 --set global.proxy.resources.requests.cpu=0 --set global.proxy.resources.requests.memory=0"
        KUBECONFIG: ((KUBECONFIG))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            istio-installer/bin/cleanup.sh
            istio-installer/bin/install.sh
    
  - name: test-after-install-old-master
    serial_groups: [ cluster ]
    plan:
    - get: istio-installer
      passed: [ install-old-master ]
      trigger: true
    - get: istio-master
      trigger: false
    - get: 24h
      trigger: true
      passed: [ install-old-master ]
    - task: install-bookinfo
      params:
        KUBECONFIG: ((KUBECONFIG))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-master
            path: src/github.com/istio/istio
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            istio-installer/bin/test.sh --skip-cleanup src/github.com/istio/istio/

  - name: update
    serial_groups: [ cluster ]
    plan:
    - get: 24h
      trigger: true
      passed: [ test-after-install-old-master ]
    - get: istio-installer
      passed: [ test-after-install-old-master ]
      trigger: true
    - task: update-master-daily
      config:
        platform: linux
        params: *params-master-daily
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            export REMOVE_OLD_CONTROL=true
            istio-installer/bin/install.sh
            istio-installer/bin/install.sh switch_istio_control
  
  - name: test-after-update
    serial_groups: [ cluster ]
    plan:
    - get: 24h
      trigger: true
      passed: [ update ]
    - get: istio-installer
      passed: [ update ]
      trigger: true
    - get: istio-master
    - task: install-bookinfo
      params:
        KUBECONFIG: ((KUBECONFIG))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-master
            path: src/github.com/istio/istio
          - name: istio-installer
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            istio-installer/bin/test.sh --skip-cleanup src/github.com/istio/istio/
