apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-telemetry
    istio: mixer
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.mixer.telemetry.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: istio-telemetry
      istio: mixer
      istio-mixer-type: telemetry
  template:
    metadata:
      labels:
        app: istio-telemetry
        istio: mixer
        istio-mixer-type: telemetry
      annotations:
        sidecar.istio.io/inject: "false"
{{- with .Values.mixer.telemetry.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: istio-mixer-service-account
      volumes:
      - name: istio-certs
        secret:
          secretName: istio.istio-mixer-service-account
          optional: true
      - name: uds-socket
        emptyDir: {}
      - name: telemetry-envoy-config
        configMap:
          name: telemetry-envoy-config

    {{- if .Values.mixer.telemetry.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.mixer.telemetry.nodeSelector | indent 8 }}
    {{- end }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
      containers:
      - name: mixer
{{- if contains "/" .Values.mixer.telemetry.image }}
        image: "{{ .Values.mixer.telemetry.image }}"
{{- else }}
        image: "{{ .Values.global.hub }}/{{ .Values.mixer.telemetry.image }}:{{ .Values.global.tag }}"
{{- end }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 15014
        - containerPort: 42422
        args:
          - --address
          - unix:///sock/mixer.socket
{{- if .Values.global.useMCP }}
    {{- if .Values.global.controlPlaneSecurityEnabled}}
          - --configStoreURL=mcp://localhost:15019
    {{- else }}
          - --configStoreURL=mcp://istio-galley.{{ .Values.global.istioNamespace }}.svc:9901
    {{- end }}
{{- else }}
          - --configStoreURL=k8s://?ns={{ .Release.Namespace }}
{{- end }}
          - --configDefaultNamespace={{ .Release.Namespace }}
          {{- if .Values.global.tracer.zipkin.address }}
          - --trace_zipkin_url=http://{{- .Values.global.tracer.zipkin.address }}/api/v1/spans
          {{- else }}
          - --trace_zipkin_url=http://zipkin:9411/api/v1/spans
          {{- end }}
        {{- if .Values.mixer.telemetry.env }}
        env:
        {{- range $key, $val := .Values.mixer.telemetry.env }}
        - name: {{ $key }}
          value: "{{ $val }}"
        {{- end }}
        {{- end }}
        resources:
{{- if .Values.mixer.telemetry.resources }}
{{ toYaml .Values.mixer.telemetry.resources | indent 10 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 10 }}
{{- end }}
        volumeMounts:
{{- if .Values.global.useMCP }}
        - name: istio-certs
          mountPath: /etc/certs
          readOnly: true
{{- end }}
        - name: uds-socket
          mountPath: /sock
        livenessProbe:
          httpGet:
            path: /version
            port: 15014
          initialDelaySeconds: 5
          periodSeconds: 5

      - name: istio-proxy
{{- if contains "/" .Values.global.proxy.image }}
        image: "{{ .Values.global.proxy.image }}"
{{- else }}
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
{{- end }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 9091
        - containerPort: 15004
        - containerPort: 15090
          protocol: TCP
          name: http-envoy-prom
        args:
        - proxy
{{- if .Values.global.proxy.proxyDomain }}
        - --domain
        - {{ .Values.global.proxy.proxyDomain }}
{{- end }}
        - --serviceCluster
        - istio-telemetry
        - --templateFile
        - /var/lib/envoy/envoy.yaml.tmpl
      {{- if .Values.global.controlPlaneSecurityEnabled }}
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
      {{- else }}
        - --controlPlaneAuthPolicy
        - NONE
      {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        resources:
{{- if .Values.global.proxy.resources }}
{{ toYaml .Values.global.proxy.resources | indent 10 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: telemetry-envoy-config
          mountPath: /var/lib/envoy
        - name: istio-certs
          mountPath: /etc/certs
          readOnly: true
        - name: uds-socket
          mountPath: /sock
