prometheus:
  enabled: true
  replicaCount: 1
  hub: docker.io/prom
  tag: v2.3.1
  retention: 6h

  # Controls the frequency of prometheus scraping
  scrapeInterval: 15s

  telemetryNamespaces:
    - istio-telemetry-master

