apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: istio-citadel11
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-citadel11
subjects:
  - kind: ServiceAccount
    name: istio-citadel11-service-account
    namespace: {{ .Release.Namespace }}
