apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: istio-citadel11
  namespace: {{ .Release.Namespace }}
  labels:
    app: citadel
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "watch", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
