apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: grafana
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      orgId: 1
{{- if .Values.grafana.prometheusNamespace }}
      url: http://prometheus.{{ .Values.grafana.prometheusNamespace }}:9090
{{ else }}
      url: http://prometheus:9090
{{- end }}
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 5s
      editable: true

{{- if .Values.grafana.datasources }}
    -
  {{- range $key, $value := .Values.grafana.datasources }}
{{ toYaml $value | indent 6 }}
  {{- end -}}
{{- end }}


{{- if .Values.grafana.dashboardProviders }}
  {{- range $key, $value := .Values.grafana.dashboardProviders }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}
