

mixer:
  policy:
    image: mixer


    replicaCount: 1
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    cpu:
      targetAverageUtilization: 80

    podAnnotations: {}

  env:
    GODEBUG: gctrace=1

  adapters:
    kubernetesenv:
      enabled: true
