mixer:
  policy:
    image: mixer

    env:
      GODEBUG: gctrace=2

    replicaCount: 1
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    cpu:
      targetAverageUtilization: 80

    podAnnotations: {}

adapters:
  kubernetesenv:
    enabled: true
