galley:
  image: galley
  replicaCount: 1

  resources:
    requests:
      cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

  # TODO: Galley appears to use the mesh config - need to find which fields are used and need to be configured.
  mesh: {}

  configValidation: true
