{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-policy
    release: {{ .Release.Name }}
    istio: mixer
    istio-mixer-type: policy
spec:
{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
  minAvailable: 1
{{- end }}
  selector:
    matchLabels:
      app: istio-policy
      release: {{ .Release.Name }}
      istio: mixer
      istio-mixer-type: policy
---
{{- end }}