# For telemetry addon gateways
{{ if .Values.gateways.kiali_gateway.enabled}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-kiali-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
    release: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15029
        name: http-kiali
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: sds
        privateKey: sds
        credentialName: telemetry-gw-cert
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtual-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
    release: {{ .Release.Name }}
spec:
  hosts:
    - "*"
  gateways:
    - istio-kiali-gateway
  http:
    - match:
        - port: 15029
      route:
        - destination:
            host: kiali.{{ .Release.Namespace }}.svc.{{ .Values.global.proxy.clusterDomain }}
            port:
              number: 20001
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
    release: {{ .Release.Name }}
spec:
  host: kiali.{{ .Release.Namespace }}.svc.{{ .Values.global.proxy.clusterDomain }}
  trafficPolicy:
    tls:
      mode: DISABLE
---
{{- end }}
