{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
{{- if $gateway.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  {{- if $gateway.podDisruptionBudget }}
  {{ include "podDisruptionBudget.spec" $gateway.podDisruptionBudget }}
  {{- end }}
selector:
  matchLabels:
    app: ingressgateway
{{- end }}
