{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
{{- if $gateway.sds.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-sds
  namespace: {{ $.Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-sds
subjects:
- kind: ServiceAccount
  name: default
---
{{- end }}
