sidecarInjectorWebhook:
  # sidecar-injector webhook configuration.
  # If down, new pods will fail to start or restart for a short time, but they will
  # retry.
  replicaCount: 1

  # This enables injection of sidecar in all namespaces,
  # with the exception of namespaces with "istio-injection:disabled" annotation
  # Only one environment should have this enabled.
  enableNamespacesByDefault: false



telemetry:
  # Will not define mixerCheckServer and mixerReportServer
  enabled: true

policy:
  # Will not define mixerCheckServer and mixerReportServer
  enabled: true


# If set, no iptable init will be added. It assumes CNI is installed.
# TODO: rename to 'enableIptables' or add 'interceptionMode: CNI'
istio_cni:
  enabled: false

# Debug level for envoy and pilot-agent. Can be set to 'debug' for very verbose
# messages.
debug: info

# Mesh config values affecting injection. See the api - this is just the subset
# needed for injection.
mesh:

  # TCP connection timeout when connecting to pilot
  connectTimeout: 10s

  # These settings that determine how long an old Envoy
  # process should be kept alive after an occasional reload.
  drainDuration: 45s
  parentShutdownDuration: 1m0s

  #
  # Set concurrency to a specific number to control the number of Proxy worker threads.
  # If not set (default), then start worker thread for each CPU thread/core.
  #concurrency:

  interceptionMode: REDIRECT


## Backward compat

mixer:
  policy:
